### ISSUE TITLE
Allow suppression of elements in rendered example resources

### ISSUE THREAD

**Issue by masnick** [HL7/fhir-ig-publisher#293]
For the [SMART Health Card Vaccination IG](https://github.com/dvci/vaccine-credential-ig), we instruct implementers to not include `Resource.id`, `Resource.meta`, and `Resource.text` in resources.

We would like the ability to optionally suppress the inclusion of these elements in the rendered example resources generated by the IG Publisher. This would allow us to create examples that conform to our IG within the IG Publisher build workflow.

[Discussion on Zulip](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Example.20resources.20without.20id.2Fmeta.2Eprofile)

**Comment by lmckenzi** [comment]
Proposal: Define a new 'internal' extension called 'suppress' that can appear on Resource.id, Resource.meta, and Resource.meta.profile.  It would be an error if this appeared on a non-example. The result would be that when serializing the instance to output - either as raw XML/JSON/TTL or the marked up version of it, those two elements would be removed.  The id would be *retained* though when storing in the IG package and the profiles would be used internally as part of validation.

@grahamegrieve any reason why this couldn't work?

**Comment by lmckenzi** [comment]
Grahame has added an ability to provide a list of resources in an IG that should 'render' with their id being removed.  The id is still actually there for purposes of creating packages, resolving links, etc.

We don't need to do anything with meta.profile because this will be addressed by a combination of https://jira.hl7.org/browse/FHIR-23965 and inter-version extensions which will allow an IG to declare multiple exampleCanonicals for an instance without needing to set meta.profile to force validation.
