### ISSUE TITLE
Bundle snapshot includes full copy of profiles from slices

### ISSUE THREAD

**Issue by masnick** [HL7/fhir-ig-publisher#334]
Between the STU2 ballot build for mCODE (back in April 2021) and now, it appears that the snapshot of our Bundle profile now includes the contents of the **entirety** of each profile under `entry:sliceName.resource`. Here's an example:

- The [STU2 ballot build](http://hl7.org/fhir/us/mcode/2021May/StructureDefinition-mcode-patient-bundle.html) does not have any child elements off `resource`.
- The [current CI build](https://build.fhir.org/ig/HL7/fhir-mCODE-ig/branches/master/StructureDefinition-mcode-patient-bundle.html) has an entire copy of each slices profile inside `resource`.

This has knock-on effects like causing the bundle to be erroneously listed as referencing value sets ([example](https://build.fhir.org/ig/HL7/fhir-mCODE-ig/branches/master/ValueSet-elixhauser-cancer-leukemia-vs.html):

<img width="734" alt="screenshot of value set" src="https://user-images.githubusercontent.com/110426/141808255-37d2a764-2aa0-4bc9-8978-ff096e7b8578.png">

We are ready to publish STU2 (going to FMG on Wednesday, Nov 17) pending resolution of this issue.

**Comment by lmckenzi** [comment]
This is caused by changes to the profile, not changes to the tools.  The snapshot generator *always* walks into every element if any of the children have been constrained.  If you don't want all the children of an element to appear in the snapshot, you can't constrain any of them.  References have always been driven by what's in the snapshot.  We *could* look at driving off differential instead or perhaps some combination (direct references vs. inherited references).  If this is something you'd like to see, please start a conversation on Zulip, which might lead to a new Git issue.
