### ISSUE TITLE
Warn when an element with a choice of data types has a binding

### ISSUE THREAD

**Issue by RichardTON** [HL7/fhir-ig-publisher#384]
When an element with a choice of data types has a binding issue a warning that the binding will apply to all of the bindable data types: code, Coding, CodeableConcept, string and Quantity, according to http://hl7.org/fhir/R4/terminologies.html.

See Zulip https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Binding.20element.20with.20a.20choice.20of.20types

**Comment by lmckenzi** [comment]
Have raised https://jira.hl7.org/browse/FHIR-48480
We think this should be handled in the core spec rather than in the tools.  However, we have also raised this ticket: https://github.com/hapifhir/org.hl7.fhir.core/issues/1760

in the HAPI validator for it to be added as a check for artifacts authored prior to R6
