### ISSUE TITLE
Publisher ignores user specified paths in IG

### ISSUE THREAD

**Issue by znatty22** [HL7/fhir-ig-publisher#44]
# Issue
It seems like the publisher expects a certain folder/file structure and breaks if the expectation is not met in some cases. 

# Example Error
For example, if I move the sample-ig's [ignoreWarnings.txt](https://github.com/FHIR/sample-ig/blob/master/input/ignoreWarnings.txt) out of the input folder a `FileNotFoundException` (regardless of whether I specify the new path as a parameter in the IG resource)

Similarly, if I rename the [input](https://github.com/FHIR/sample-ig/tree/master/input) folder to something else (e.g. source), and specify the parameters (e.g. path-resource: source/resources) in my IG, the publisher still breaks because its looking for the resources in `input/resources`. Does the same thing for other things it needs like `input/_includes`. 

See attached log 
[ig-publisher.log](https://github.com/HL7/fhir-ig-publisher/files/3923372/ig-publisher.log)

**Comment by grahamegrieve** [comment]
This is an issue in the template - and probably by design

**Comment by lmckenzi** [comment]
It's absolutely by design.  The purpose of a template is to set expectations about where source files will exist (both folder names and naming convention) and what the result will look like.  This consistency eases maintenance as content across IGs is always in the same place and also eases things for reviewers as published content looks the same.

If you're wanting to change where files are located or what they're called, you'd need to define your own template - or at least a delta on the base template.
