### ISSUE TITLE
While using publish-update for release, duplicate files are produced

### ISSUE THREAD

**Issue by aditya-n-invcr** [HL7/fhir-ig-publisher#447]
When using `publish-update` for releasing a non hl7-IG, duplicate files start getting produced in the web-root folder.

For example if there's a file named `StructureDefinition-acute-care-medicationadministration.xml`, after running `publish-update`, the following two files  namely `StructureDefinition-acute-care-medicationadministration.xml1` and `StructureDefinition-acute-care-medicationadministration.xml1` get produced.

On examining the contents they're exactly the same as the original `StructureDefinition-acute-care-medicationadministration.xml`. Generating these duplicates don't seem to make much sense. Let me know if I'm missing something here.

**Expected behavior**: Duplicate files shouldn't be produced.

**Comment by grahamegrieve** [comment]
how do two files with exactly the same name get produced?

**Comment by aditya-n-invcr** [comment]
> how do two files with exactly the same name get produced?

I'm sry that was a typo. The two files are `StructureDefinition-acute-care-medicationadministration.xml1` and `StructureDefinition-acute-care-medicationadministration.xml2`

**Comment by lmckenzi** [comment]
The .xml1 and .xml2 file are produced for a reason.  In the web-config files, mime types are tied to file extensions.  Because there are different mime types that can come back - application/xml is tied to .xml, application/xml+fhir is tied to .xml1 and application/fhir+xml is tied to .xml2.  We must have distinct file names to ensure that the mime type that comes back is the one that was requested.
Have now documented this on https://confluence.hl7.org/pages/viewpage.action?pageId=81027536#MaintainingaFHIRIGPublication-Redirections
