### ISSUE TITLE
Flag/Standard status not shown in key elements and snapshot

### ISSUE THREAD

**Issue by qligier** [HL7/fhir-ig-publisher#567]
Flags have started to be shown in `Content → Differential table`, and standard status in `Detailed Description → Differential Elements Table`:
![2022-12-07 13 51 29  dc127a3391fe](https://user-images.githubusercontent.com/3299399/206184548-1c14cc83-6e39-4114-9c30-90c2811236f6.png)
![2022-12-07 13 52 11  d9596a9c8da7](https://user-images.githubusercontent.com/3299399/206184563-fb0e4c96-f81f-49ba-9671-c512c91a9829.png)
(Example from https://build.fhir.org/ig/CARA-ch/ch-emed-epr/StructureDefinition-ch-emed-epr-medicationstatement-card.html)

This information is missing from the other tables (_key elements_ and _snapshot_):

![2022-12-07 13 51 44  43af5253c0f8](https://user-images.githubusercontent.com/3299399/206184302-efdd18f0-a0c6-438f-b4db-99635e65294c.png)
![2022-12-07 13 52 39  3f1ffdd8de46](https://user-images.githubusercontent.com/3299399/206186316-37c59238-3363-4238-96f4-e257bcc1a4fa.png)

In the same way, the _key elements_ and _snapshot_ tables in _Detailed Descriptions_ are not showing the _Summary_ information:
![2022-12-07 14 06 54 build fhir org bac96e67c3fc](https://user-images.githubusercontent.com/3299399/206187581-c0798ca6-1e6e-4fd3-8ae4-59f3ceacda26.png)

In the [official documentation](http://hl7.org/fhir/R4/medicationstatement-definitions.html):
![2022-12-07 14 06 10 hl7 org 9db52d9d1a8a](https://user-images.githubusercontent.com/3299399/206187569-88dd0da7-d535-44f1-989f-7547ff60fbfb.png)

**Comment by lmckenzi** [comment]
We have made changes to propagate the standards status to child models.  However: standard status will only be displayed on elements if it is *less* than the standards status of the artifact overall.  For example, an extension on "normative" Observation might mark Observation.focus as "trial use".  However, that same element would *not* be called out in an "STU" profile on Observation because *all* elements in the profile are considered trial use.  If/when the STU profile were to become normative, then the inherited "STU" flag on the focus element would be rendered. 

We will update the rendering process to expose the "Summary" view in the Key elements and Snapshot views.

**Comment by qligier** [comment]
Okay, that behavior makes sense, except for one case: if the artifact is set to "draft" by example, and a particular element is set to "normative", then it won't be displayed (because it's _more_, not _less_ than overall). Showing an element status only if it's not equal to the artifact status could make more sense, no?

In that particular case, I've not set any status on the MedicationStatement. I don't know which status it has; so I'll check that if the statuses still won't appear.

**Comment by grahamegrieve** [comment]
it's not valid to have an element marked as normative when the container is not normative.

**Comment by qligier** [comment]
Nothing seems to prevent that now, though.
![2022-12-16 09 34 00  294e8c3bb5bb](https://user-images.githubusercontent.com/3299399/208057549-753b9664-53d0-474b-b9e0-4f3cc2299401.png)

So:
1. This example should be invalid;
2. And the normative flag won't appear anymore because it's not less than the "draft" Composition.

Right?

Random test with:
```xml
<StructureDefinition xmlns="http://hl7.org/fhir">
   ...
   <extension url="http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status">
      <valueCode value="draft"/>
   </extension>
   <differential>
      <element id="Composition.identifier.system">
         <extension url="http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status">
            <valueCode value="normative"/>
         </extension>
      </element>
   </differential>
</StructureDefinition>
```

**Comment by lmckenzi** [comment]
"Normative" is only going to be asserted by HL7 specifications or others subject to ANSI review, so it's not something that would be asserted by non-HL7 publishers.  If the CH profile was published by an affiliate, they're using 'normative' incorrectly.

The rules around what can be normative vs. not are established by HL7, not constraints on the invariant.  You're correct that there should *never* be a Normative flag on an individual element because element flags are always less than the artifact as a whole and Normative can't ever be "less than".

**Comment by qligier** [comment]
Okay, thank you for the clarification!
The example was just me poking around, the profile doesn't contain such code. I'm extending a profile managed by HL7 Switzerland, I'm not technically bound to these rules but they seem good guidelines to follow, even more if the IG Publisher applies some of these.

**Comment by lmckenzi** [comment]
Table stuff now seems to be fixed, but data dictionary still needs to be dealt with.

**Comment by lmckenzi** [comment]
Correction on rules for Normative - I over-stated the rules.  If another organization wishes to use the term "Normative", they're free to do so.  However, what it means may vary and it won't be under the auspices of HL7's rules/oversight.

**Comment by lmckenzi** [comment]
https://github.com/hapifhir/org.hl7.fhir.core/pull/1813

**Comment by lmckenzi** [comment]
Done
