### ISSUE TITLE
Raise a warning if modifier elements aren't mustSupport if mustSupports are present

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#84]
If mustSupports are declared in a profile, raise an error for each element in the snapshot that is a modifier element but isn't flagged as mustSupport.  (exclude modifierExtension and implicit rules unless the corresponding element appears in the differential)

**Comment by grahamegrieve** [comment]
I don't see why modifier elements should be must-support = true

**Comment by lmckenzi** [comment]
They don't *have* to be.  But it's only safe for them to *not* be mustSupport if the use-case the profile is trying to enable is one where they're safe to ignore.  If that turns out to be the case, the warning can be added to the ignore file.  However, in most cases, I'd expect the mustSupport elements to either be marked as mustSupport, constrained to a fixed value or prohibited.  (A warning would only be needed if one of those things hadn't been done.)

**Comment by lmckenzi** [comment]
Decision is that the new "key elements" view accomplishes the intention here - draw attention of both authors and implementers to 'in-scope' modifier elements.  We think that having warning or info messages would just create a lot of noise.  No further action.
