### ISSUE TITLE
Retired Extensions don't display as retired

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#951]
When an extension is indicated in the StructureDefinition.status as retired; the narrative produced by the IG Publisher does not indicate this at all. The validator does complain about use of a retired extension.

FHIR-46850 indicates further problems caused by the standards-status that I am not covering here. 

Here I am only indicating that the artifact status, especially status values like retired or deprecated; should show prominently on the narrative generated by the IG Publisher. So, possibly other status values should cause the narrative to look different.

**Comment by grahamegrieve** [comment]
why isn't this a template issue?

**Comment by JohnMoehrke** [comment]
There is an indication in the header box if it is shown

![image](https://github.com/user-attachments/assets/9066c96c-f298-4775-a60d-c8e7c00d9165)

**Comment by JohnMoehrke** [comment]
but not in the extension pack

![image](https://github.com/user-attachments/assets/2f2dbb64-e098-4566-913b-48838d06fb2a)

**Comment by lmckenzi** [comment]
The issue here is that the standards-status and status don't align.  If the standards-status said "Withdrawn", it would have been pink.  (standards-status trumps status when it comes to rendering.)  There's no change required here - except perhaps to the merge process for extensions, which should check for new QA issues before merging a change.  John will bring that up on FMG.
