### ISSUE TITLE
Improve CapabilityStatement rendering to visualise chained searches, comparators, modifiers and other SearchParameter specifications 

### ISSUE THREAD

**Issue by dbojicic** [HL7/fhir-ig-publisher#965]
Consider enhancement to the IG Publisher (and possibly templates?) to visualise chained searches expectations. For example, when a reference search parameter supports chained searches (e.g. `AllergyIntolerance?patient.identifier`), the IG Publisher indicates this clearly in the rendered CapabilityStatement. 

Similarly, clearly indicate in the rendered CapabilityStatement whether search parameters support multipleAnd, multipleOr, comparators etc. 

This would provide a more complete and informative representation of search capabilities in the CapabilityStatement.

**Comment by lmckenzi** [comment]
At this point, we'd prefer to have the rendering of the details of a SearchParameter on the SearchParameter page, not to suck it into the narrative for the referencing CapabilityStatement.  We don't bring in the details of profiles or operation definitions that are referenced by a CapabilityStatement and it seems odd to treat SearchParameters differently.  (The "what chaining do you support?" is actually a property of the CapabilityStatement, which is why it renders there.)
